// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzaUcekwiLZMLYNH2rHHSdGr-jJed0hE',
    appId: '1:792868097322:android:24edf4b3829e71bb982253',
    messagingSenderId: '792868097322',
    projectId: 'ftcforum',
    storageBucket: 'ftcforum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk6vuhrp_l-0-bkfHfDRQLp2TEjlKS4j8',
    appId: '1:792868097322:ios:c4facb8a6005faed982253',
    messagingSenderId: '792868097322',
    projectId: 'ftcforum',
    storageBucket: 'ftcforum.appspot.com',
    iosClientId: '792868097322-2ppvc4nnl8vaasl247as811rh36q63rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ftcForum',
  );
}
